name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Build Docker images for tests
        run: |
          docker build -f ./AuthService/Dockerfile -t mysocialnetwork-auth-service:latest .
          docker tag mysocialnetwork-auth-service:latest ${{ secrets.DOCKER_USERNAME }}/mysocialnetwork-auth-service:latest
          docker build -f ./UserProfileService/Dockerfile -t mysocialnetwork-user-profile-service:latest .
          docker tag mysocialnetwork-user-profile-service:latest ${{ secrets.DOCKER_USERNAME }}/mysocialnetwork-user-profile-service:latest
          docker build -f ./PostService/Dockerfile -t mysocialnetwork-post-service:latest .
          docker tag mysocialnetwork-post-service:latest ${{ secrets.DOCKER_USERNAME }}/mysocialnetwork-post-service:latest
          docker build -f ./ApiGateway/Dockerfile -t mysocialnetwork-api-gateway-service:latest .
          docker tag mysocialnetwork-api-gateway-service:latest ${{ secrets.DOCKER_USERNAME }}/mysocialnetwork-api-gateway-service:latest

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

  push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mysocialnetwork-auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mysocialnetwork-user-profile-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mysocialnetwork-post-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mysocialnetwork-api-gateway-service:latest
